export const Routes = {
  OtpVerification: "/otp-verfication",
  login: "/login",
  signUp: "/",
  parentHome: "/parent/home",
  parentLessons: "/parent/lessons",
  parentDrivingAbility: "/parent/driving-ability",
  resources: "/parent/resources",
  contacts: "/parent/contacts",
  AddContact: "/parent/add-contact",
  relativeLogs: "/parent/relative-logs",
  parentInbox: "/parent/inbox",
  parentPayement: "/parent/payement",
  parentProfile: "/parent/profile",
  parentInboxById: (id) => `/parent/inbox/${id}`,
};